import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.sql.*;
import java.util.Map;
import javax.swing.JOptionPane;

public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form sign_up
     */
    public sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pswd = new javax.swing.JPasswordField();
        cfpswd = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 81, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 197, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 222, 251, 18));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 255, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 310, -1, -1));

        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 78, 183, -1));

        uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unameFocusLost(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 194, 183, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 280, 251, 18));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 338, 166, 18));

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CREATE YOUR ACCOUNT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 240, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Already have an account?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 377, -1, -1));

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Log in");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 377, -1, -1));

        pswd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswdFocusLost(evt);
            }
        });
        getContentPane().add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 252, 183, -1));

        cfpswd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cfpswdFocusLost(evt);
            }
        });
        getContentPane().add(cfpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 310, 183, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Last Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 139, -1, -1));

        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 136, 183, -1));

        jLabel12.setPreferredSize(new java.awt.Dimension(5, 16));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 106, 166, 18));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 164, 183, 18));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign up.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

                    dispose();
                    sign_in x = new sign_in();
                    x.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        
        Font font = jLabel10.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel10.setFont(font.deriveFont(attributes));
        
        jLabel10.setForeground(Color.MAGENTA);
        
    }//GEN-LAST:event_jLabel10MouseEntered

    private void unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocusLost

      {
        try 
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/login_database","Muchiri","Muchiri1234!");
            
            String query = "SELECT * FROM accounts WHERE uname =?";
            PreparedStatement pstmt = conn.prepareStatement(query);;
           
            pstmt.setString(1, uname.getText());
            
            ResultSet resultset = pstmt.executeQuery();
            
            if(uname.getText().isBlank())
                        {
                                jLabel3.setText("This is a required field");
                                jLabel3.setForeground(Color.RED);
                        }
            else if(resultset.next()==false)
                        {
                                jLabel3.setText("Valid Username");
                                jLabel3.setForeground(Color.GREEN);
                        }
                else
                        {
                                jLabel3.setText("Username already exists...Choose another");
                                jLabel3.setForeground(Color.RED);
                        }
        } 
        
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        
    }
    }//GEN-LAST:event_unameFocusLost

    private void pswdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdFocusLost
        
        String p = String.valueOf(pswd.getPassword());
        if(p.length()<6)
        {
            jLabel6.setText("Password should have at least 6 characters");
            jLabel6.setForeground(Color.RED);
        }
       else
        {
            jLabel6.setText("Strong Password");
            jLabel6.setForeground(Color.GREEN);
        }
        
    }//GEN-LAST:event_pswdFocusLost

    private void cfpswdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cfpswdFocusLost
        
        String cp = String.valueOf(cfpswd.getPassword());
        String p = String.valueOf(pswd.getPassword());
        
        if(String.valueOf(cfpswd.getPassword()).isBlank())
        {
            jLabel7.setText("This is a required field");
            jLabel7.setForeground(Color.RED);
        }
        else if(cp.equals(p))
        {
            jLabel7.setText("Valid confirmation");  
            jLabel7.setForeground(Color.GREEN);
        }
        else
        {
            jLabel7.setText("Passwords do not match");  
            jLabel7.setForeground(Color.RED);
        }
        
    }//GEN-LAST:event_cfpswdFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          try
        {
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/login_database","Muchiri","Muchiri1234!");
        
        String insert="INSERT INTO accounts VALUES(?,?,?,?)";
        
        PreparedStatement pstmt= conn.prepareStatement(insert);
        
      
        pstmt.setString(1,fname.getText());
        
        pstmt.setString(2,lname.getText());
        
        pstmt.setString(3,uname.getText());
        
        pstmt.setString(4,String.valueOf(pswd.getPassword()));
        
                if(fname.getText().isBlank() || lname.getText().isBlank() || uname.getText().isBlank() || String.valueOf(pswd.getPassword()).isBlank() )
                {
             
              JOptionPane.showMessageDialog(null,"Make sure you have filled all the required fields");
                }
                else
                {
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Account created successfully") ;
                }
                
         }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        if (fname.getText().isBlank())
        {
            jLabel12.setText("This is a required field");
            jLabel12.setForeground(Color.RED);
        }
        else
        {
            jLabel12.setText("");
        }
    }//GEN-LAST:event_fnameFocusLost

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
        if (lname.getText().isBlank())
        {
            jLabel13.setText("This is a required field");
            jLabel13.setForeground(Color.RED);
        }
        else
        {
            jLabel13.setText("");
        }
    }//GEN-LAST:event_lnameFocusLost

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        Font font = jLabel10.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        jLabel10.setFont(font.deriveFont(attributes));
        jLabel10.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel10MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cfpswd;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
